In [1]:
import pandas as pd

train_df = pd.read_csv('sentiment-analysis-on-movie-reviews/train.tsv', sep='\t', header=0)
test_df = pd.read_csv('sentiment-analysis-on-movie-reviews/test.tsv', sep='\t', header=0)


print(train_df.shape,test_df.shape)

Phrase_list = train_df['Phrase']
Sentiment_list = train_df['Sentiment']

X_test = test_df['Phrase']


(156060, 4) (66292, 3)


In [4]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

max_len = 100
training_samples = 156000
validation_samples = 10000
max_words = 10000

texts = Phrase_list
labels = np.asarray(Sentiment_list)

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
print('Found %s unique tokens.' %len(word_index))

data = pad_sequences(sequences,maxlen= max_len)

X_test = tokenizer.texts_to_sequences(X_test)
X_test = pad_sequences(X_test,maxlen= max_len)


x_train = data[:training_samples]
y_train = labels[:training_samples]

print('x_train:',x_train)
print('x_test:',X_test)

Found 15288 unique tokens.


x_train: [[   0    0    0 ...    3    2   42]
 [   0    0    0 ...   13    1 2976]
 [   0    0    0 ...    0    2  323]
 ...
 [   0    0    0 ...    3  353  330]
 [   0    0    0 ...    0  437  173]
 [   0    0    0 ...    0    0  173]]
x_test: [[   0    0    0 ...  614 1024  392]
 [   0    0    0 ...  614 1024  392]
 [   0    0    0 ...    0    0   16]
 ...
 [   0    0    0 ...    2  126 5916]
 [   0    0    0 ...    2  126 5916]
 [   0    0    0 ...    0  373 2014]]


In [5]:
from keras.utils import to_categorical
y_train = to_categorical(y_train)
print(y_train)


[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [7]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding,SimpleRNN
max_features = 10000


model = Sequential()
model.add(Embedding(max_features,32))
model.add(SimpleRNN(32))
model.add(Dense(5,activation='softmax'))
model.compile(optimizer='rmsprop', loss = 'categorical_crossentropy',metrics=['acc'])


history = model.fit(x_train, y_train,
                    epochs=100,
                    batch_size=128,
                    validation_split=0.2

                    )


Train on 124800 samples, validate on 31200 samples
Epoch 1/100


   128/124800 [..............................] - ETA: 34:05 - loss: 1.5156 - acc: 0.5312

   256/124800 [..............................] - ETA: 17:26 - loss: 1.4951 - acc: 0.5391

   512/124800 [..............................] - ETA: 9:02 - loss: 1.4736 - acc: 0.5137 



   640/124800 [..............................] - ETA: 7:25 - loss: 1.4758 - acc: 0.5000

   896/124800 [..............................] - ETA: 5:25 - loss: 1.4517 - acc: 0.5045

  1152/124800 [..............................] - ETA: 4:23 - loss: 1.4280 - acc: 0.5095

  1280/124800 [..............................] - ETA: 4:01 - loss: 1.4165 - acc: 0.5141

  1536/124800 [..............................] - ETA: 3:27 - loss: 1.4027 - acc: 0.5130

  1792/124800 [..............................] - ETA: 3:03 - loss: 1.3893 - acc: 0.5134

  2048/124800 [..............................] - ETA: 2:44 - loss: 1.3872 - acc: 0.5059

  2304/124800 [..............................] - ETA: 2:30 - loss: 1.3716 - acc: 0.5130

  2432/124800 [..............................] - ETA: 2:26 - loss: 1.3660 - acc: 0.5140

  2560/124800 [..............................] - ETA: 2:21 - loss: 1.3612 - acc: 0.5141

  2688/124800 [..............................] - ETA: 2:16 - loss: 1.3575 - acc: 0.5141



  2944/124800 [..............................] - ETA: 2:08 - loss: 1.3456 - acc: 0.5163

  3072/124800 [..............................] - ETA: 2:05 - loss: 1.3428 - acc: 0.5163

  3200/124800 [..............................] - ETA: 2:02 - loss: 1.3376 - acc: 0.5181



  3456/124800 [..............................] - ETA: 1:55 - loss: 1.3297 - acc: 0.5205

  3712/124800 [..............................] - ETA: 1:50 - loss: 1.3274 - acc: 0.5197

  3968/124800 [..............................] - ETA: 1:45 - loss: 1.3226 - acc: 0.5189

  4096/124800 [..............................] - ETA: 1:43 - loss: 1.3198 - acc: 0.5186



  4224/124800 [>.............................] - ETA: 1:41 - loss: 1.3176 - acc: 0.5187

  4352/124800 [>.............................] - ETA: 1:40 - loss: 1.3144 - acc: 0.5188



  4608/124800 [>.............................] - ETA: 1:36 - loss: 1.3166 - acc: 0.5148

  4864/124800 [>.............................] - ETA: 1:33 - loss: 1.3138 - acc: 0.5138

  5120/124800 [>.............................] - ETA: 1:30 - loss: 1.3112 - acc: 0.5115

  5376/124800 [>.............................] - ETA: 1:27 - loss: 1.3066 - acc: 0.5115

  5632/124800 [>.............................] - ETA: 1:25 - loss: 1.3014 - acc: 0.5130

  5888/124800 [>.............................] - ETA: 1:22 - loss: 1.3019 - acc: 0.5114

  6144/124800 [>.............................] - ETA: 1:21 - loss: 1.2980 - acc: 0.5122

  6272/124800 [>.............................] - ETA: 1:20 - loss: 1.2981 - acc: 0.5107

  6400/124800 [>.............................] - ETA: 1:19 - loss: 1.2987 - acc: 0.5098



  6656/124800 [>.............................] - ETA: 1:17 - loss: 1.2973 - acc: 0.5084

  6784/124800 [>.............................] - ETA: 1:17 - loss: 1.2952 - acc: 0.5087

  6912/124800 [>.............................] - ETA: 1:16 - loss: 1.2936 - acc: 0.5097

  7168/124800 [>.............................] - ETA: 1:14 - loss: 1.2925 - acc: 0.5092

  7424/124800 [>.............................] - ETA: 1:13 - loss: 1.2914 - acc: 0.5084

  7680/124800 [>.............................] - ETA: 1:12 - loss: 1.2915 - acc: 0.5077

  7936/124800 [>.............................] - ETA: 1:11 - loss: 1.2895 - acc: 0.5079

  8192/124800 [>.............................] - ETA: 1:09 - loss: 1.2872 - acc: 0.5085

  8448/124800 [=>............................] - ETA: 1:08 - loss: 1.2850 - acc: 0.5091

  8576/124800 [=>............................] - ETA: 1:08 - loss: 1.2825 - acc: 0.5094

  8832/124800 [=>............................] - ETA: 1:07 - loss: 1.2801 - acc: 0.5095

  9088/124800 [=>............................] - ETA: 1:06 - loss: 1.2805 - acc: 0.5086

  9216/124800 [=>............................] - ETA: 1:06 - loss: 1.2791 - acc: 0.5087

  9472/124800 [=>............................] - ETA: 1:05 - loss: 1.2748 - acc: 0.5099



  9728/124800 [=>............................] - ETA: 1:04 - loss: 1.2718 - acc: 0.5117

  9984/124800 [=>............................] - ETA: 1:03 - loss: 1.2691 - acc: 0.5129

 10240/124800 [=>............................] - ETA: 1:02 - loss: 1.2646 - acc: 0.5147

 10496/124800 [=>............................] - ETA: 1:02 - loss: 1.2646 - acc: 0.5140

 10624/124800 [=>............................] - ETA: 1:01 - loss: 1.2643 - acc: 0.5144

 10752/124800 [=>............................] - ETA: 1:01 - loss: 1.2638 - acc: 0.5148

 11008/124800 [=>............................] - ETA: 1:01 - loss: 1.2623 - acc: 0.5152



 11264/124800 [=>............................] - ETA: 1:00 - loss: 1.2602 - acc: 0.5161

 11520/124800 [=>............................] - ETA: 59s - loss: 1.2577 - acc: 0.5168 

 11776/124800 [=>............................] - ETA: 59s - loss: 1.2571 - acc: 0.5170

 12032/124800 [=>............................] - ETA: 58s - loss: 1.2560 - acc: 0.5170

 12288/124800 [=>............................] - ETA: 57s - loss: 1.2559 - acc: 0.5165

 12544/124800 [==>...........................] - ETA: 57s - loss: 1.2563 - acc: 0.5154

 12800/124800 [==>...........................] - ETA: 56s - loss: 1.2567 - acc: 0.5148

 12928/124800 [==>...........................] - ETA: 56s - loss: 1.2565 - acc: 0.5145

 13184/124800 [==>...........................] - ETA: 55s - loss: 1.2549 - acc: 0.5151

 13440/124800 [==>...........................] - ETA: 55s - loss: 1.2531 - acc: 0.5158



 13696/124800 [==>...........................] - ETA: 55s - loss: 1.2527 - acc: 0.5163

 13952/124800 [==>...........................] - ETA: 54s - loss: 1.2518 - acc: 0.5164

 14208/124800 [==>...........................] - ETA: 54s - loss: 1.2500 - acc: 0.5172

 14336/124800 [==>...........................] - ETA: 53s - loss: 1.2498 - acc: 0.5170



 14592/124800 [==>...........................] - ETA: 53s - loss: 1.2496 - acc: 0.5167

 14848/124800 [==>...........................] - ETA: 52s - loss: 1.2489 - acc: 0.5177

 15104/124800 [==>...........................] - ETA: 52s - loss: 1.2489 - acc: 0.5175

 15360/124800 [==>...........................] - ETA: 52s - loss: 1.2494 - acc: 0.5170

 15488/124800 [==>...........................] - ETA: 52s - loss: 1.2486 - acc: 0.5174

 15744/124800 [==>...........................] - ETA: 51s - loss: 1.2473 - acc: 0.5180

 16000/124800 [==>...........................] - ETA: 51s - loss: 1.2461 - acc: 0.5191

 16256/124800 [==>...........................] - ETA: 50s - loss: 1.2455 - acc: 0.5193

 16512/124800 [==>...........................] - ETA: 50s - loss: 1.2438 - acc: 0.5197

 16640/124800 [===>..........................] - ETA: 50s - loss: 1.2434 - acc: 0.5200

 16896/124800 [===>..........................] - ETA: 50s - loss: 1.2422 - acc: 0.5202

 17152/124800 [===>..........................] - ETA: 49s - loss: 1.2418 - acc: 0.5204

 17408/124800 [===>..........................] - ETA: 49s - loss: 1.2398 - acc: 0.5216

 17536/124800 [===>..........................] - ETA: 49s - loss: 1.2397 - acc: 0.5214

 17792/124800 [===>..........................] - ETA: 48s - loss: 1.2375 - acc: 0.5227

 17920/124800 [===>..........................] - ETA: 48s - loss: 1.2375 - acc: 0.5228

 18176/124800 [===>..........................] - ETA: 48s - loss: 1.2359 - acc: 0.5237



 18304/124800 [===>..........................] - ETA: 48s - loss: 1.2355 - acc: 0.5237



 18560/124800 [===>..........................] - ETA: 48s - loss: 1.2349 - acc: 0.5240



 18688/124800 [===>..........................] - ETA: 48s - loss: 1.2337 - acc: 0.5247

 18944/124800 [===>..........................] - ETA: 47s - loss: 1.2331 - acc: 0.5245

 19200/124800 [===>..........................] - ETA: 47s - loss: 1.2331 - acc: 0.5242

 19456/124800 [===>..........................] - ETA: 47s - loss: 1.2326 - acc: 0.5245

 19712/124800 [===>..........................] - ETA: 46s - loss: 1.2315 - acc: 0.5248

 19840/124800 [===>..........................] - ETA: 46s - loss: 1.2314 - acc: 0.5248

 19968/124800 [===>..........................] - ETA: 46s - loss: 1.2309 - acc: 0.5249

 20224/124800 [===>..........................] - ETA: 46s - loss: 1.2308 - acc: 0.5249



 20480/124800 [===>..........................] - ETA: 46s - loss: 1.2302 - acc: 0.5250

 20736/124800 [===>..........................] - ETA: 46s - loss: 1.2289 - acc: 0.5256

 20992/124800 [====>.........................] - ETA: 45s - loss: 1.2275 - acc: 0.5260

 21248/124800 [====>.........................] - ETA: 45s - loss: 1.2268 - acc: 0.5259

 21376/124800 [====>.........................] - ETA: 45s - loss: 1.2267 - acc: 0.5260

 21632/124800 [====>.........................] - ETA: 45s - loss: 1.2256 - acc: 0.5262

 21888/124800 [====>.........................] - ETA: 45s - loss: 1.2259 - acc: 0.5263

 22016/124800 [====>.........................] - ETA: 44s - loss: 1.2246 - acc: 0.5268

 22272/124800 [====>.........................] - ETA: 44s - loss: 1.2241 - acc: 0.5273

 22528/124800 [====>.........................] - ETA: 44s - loss: 1.2226 - acc: 0.5281

 22784/124800 [====>.........................] - ETA: 44s - loss: 1.2221 - acc: 0.5280

 23040/124800 [====>.........................] - ETA: 44s - loss: 1.2211 - acc: 0.5283



 23296/124800 [====>.........................] - ETA: 43s - loss: 1.2199 - acc: 0.5290



 23552/124800 [====>.........................] - ETA: 43s - loss: 1.2196 - acc: 0.5290

 23808/124800 [====>.........................] - ETA: 43s - loss: 1.2180 - acc: 0.5297

 24064/124800 [====>.........................] - ETA: 43s - loss: 1.2183 - acc: 0.5294

 24320/124800 [====>.........................] - ETA: 42s - loss: 1.2188 - acc: 0.5292

 24576/124800 [====>.........................] - ETA: 42s - loss: 1.2184 - acc: 0.5289

 24832/124800 [====>.........................] - ETA: 42s - loss: 1.2181 - acc: 0.5288

 25088/124800 [=====>........................] - ETA: 42s - loss: 1.2183 - acc: 0.5287

 25344/124800 [=====>........................] - ETA: 42s - loss: 1.2182 - acc: 0.5287

 25600/124800 [=====>........................] - ETA: 41s - loss: 1.2173 - acc: 0.5291

 25856/124800 [=====>........................] - ETA: 41s - loss: 1.2173 - acc: 0.5290



 25984/124800 [=====>........................] - ETA: 41s - loss: 1.2169 - acc: 0.5292

 26112/124800 [=====>........................] - ETA: 41s - loss: 1.2169 - acc: 0.5291



 26368/124800 [=====>........................] - ETA: 41s - loss: 1.2158 - acc: 0.5293

 26624/124800 [=====>........................] - ETA: 41s - loss: 1.2157 - acc: 0.5290

 26880/124800 [=====>........................] - ETA: 40s - loss: 1.2151 - acc: 0.5291

 27136/124800 [=====>........................] - ETA: 40s - loss: 1.2154 - acc: 0.5288

 27392/124800 [=====>........................] - ETA: 40s - loss: 1.2149 - acc: 0.5290

 27648/124800 [=====>........................] - ETA: 40s - loss: 1.2144 - acc: 0.5293

 27904/124800 [=====>........................] - ETA: 40s - loss: 1.2140 - acc: 0.5294

 28160/124800 [=====>........................] - ETA: 39s - loss: 1.2138 - acc: 0.5293

 28288/124800 [=====>........................] - ETA: 39s - loss: 1.2137 - acc: 0.5292



 28544/124800 [=====>........................] - ETA: 39s - loss: 1.2131 - acc: 0.5293

 28672/124800 [=====>........................] - ETA: 39s - loss: 1.2132 - acc: 0.5293



 28800/124800 [=====>........................] - ETA: 39s - loss: 1.2131 - acc: 0.5293

 29056/124800 [=====>........................] - ETA: 39s - loss: 1.2128 - acc: 0.5293

 29312/124800 [======>.......................] - ETA: 39s - loss: 1.2131 - acc: 0.5288

 29568/124800 [======>.......................] - ETA: 38s - loss: 1.2126 - acc: 0.5287

 29824/124800 [======>.......................] - ETA: 38s - loss: 1.2123 - acc: 0.5285

 30080/124800 [======>.......................] - ETA: 38s - loss: 1.2118 - acc: 0.5288

 30336/124800 [======>.......................] - ETA: 38s - loss: 1.2107 - acc: 0.5292

 30592/124800 [======>.......................] - ETA: 38s - loss: 1.2105 - acc: 0.5291

 30848/124800 [======>.......................] - ETA: 38s - loss: 1.2104 - acc: 0.5291

 31104/124800 [======>.......................] - ETA: 37s - loss: 1.2097 - acc: 0.5297



 31360/124800 [======>.......................] - ETA: 37s - loss: 1.2093 - acc: 0.5298

 31488/124800 [======>.......................] - ETA: 37s - loss: 1.2092 - acc: 0.5298

 31744/124800 [======>.......................] - ETA: 37s - loss: 1.2085 - acc: 0.5299

 31872/124800 [======>.......................] - ETA: 37s - loss: 1.2085 - acc: 0.5298

 32128/124800 [======>.......................] - ETA: 37s - loss: 1.2080 - acc: 0.5300

 32384/124800 [======>.......................] - ETA: 37s - loss: 1.2077 - acc: 0.5299

 32640/124800 [======>.......................] - ETA: 37s - loss: 1.2078 - acc: 0.5297

 32896/124800 [======>.......................] - ETA: 36s - loss: 1.2071 - acc: 0.5300

 33024/124800 [======>.......................] - ETA: 36s - loss: 1.2072 - acc: 0.5299

 33280/124800 [=======>......................] - ETA: 36s - loss: 1.2068 - acc: 0.5299

 33536/124800 [=======>......................] - ETA: 36s - loss: 1.2066 - acc: 0.5300



 33792/124800 [=======>......................] - ETA: 36s - loss: 1.2059 - acc: 0.5303

 33920/124800 [=======>......................] - ETA: 36s - loss: 1.2054 - acc: 0.5305

 34176/124800 [=======>......................] - ETA: 36s - loss: 1.2045 - acc: 0.5310

 34432/124800 [=======>......................] - ETA: 36s - loss: 1.2046 - acc: 0.5308

 34688/124800 [=======>......................] - ETA: 35s - loss: 1.2039 - acc: 0.5313

 34944/124800 [=======>......................] - ETA: 35s - loss: 1.2032 - acc: 0.5315

 35200/124800 [=======>......................] - ETA: 35s - loss: 1.2037 - acc: 0.5314

 35456/124800 [=======>......................] - ETA: 35s - loss: 1.2035 - acc: 0.5314

 35584/124800 [=======>......................] - ETA: 35s - loss: 1.2034 - acc: 0.5315



 35712/124800 [=======>......................] - ETA: 35s - loss: 1.2036 - acc: 0.5313

 35968/124800 [=======>......................] - ETA: 35s - loss: 1.2031 - acc: 0.5316

 36224/124800 [=======>......................] - ETA: 35s - loss: 1.2024 - acc: 0.5318

 36352/124800 [=======>......................] - ETA: 35s - loss: 1.2020 - acc: 0.5320



 36480/124800 [=======>......................] - ETA: 34s - loss: 1.2022 - acc: 0.5319

 36736/124800 [=======>......................] - ETA: 34s - loss: 1.2019 - acc: 0.5319

 36992/124800 [=======>......................] - ETA: 34s - loss: 1.2015 - acc: 0.5319

 37120/124800 [=======>......................] - ETA: 34s - loss: 1.2017 - acc: 0.5317

 37376/124800 [=======>......................] - ETA: 34s - loss: 1.2012 - acc: 0.5319

 37632/124800 [========>.....................] - ETA: 34s - loss: 1.2008 - acc: 0.5320

 37888/124800 [========>.....................] - ETA: 34s - loss: 1.2008 - acc: 0.5321

 38144/124800 [========>.....................] - ETA: 34s - loss: 1.2001 - acc: 0.5323

 38400/124800 [========>.....................] - ETA: 33s - loss: 1.1997 - acc: 0.5323

 38656/124800 [========>.....................] - ETA: 33s - loss: 1.1991 - acc: 0.5328

 38912/124800 [========>.....................] - ETA: 33s - loss: 1.1990 - acc: 0.5329

 39040/124800 [========>.....................] - ETA: 33s - loss: 1.1992 - acc: 0.5327



 39168/124800 [========>.....................] - ETA: 33s - loss: 1.1994 - acc: 0.5326



 39424/124800 [========>.....................] - ETA: 33s - loss: 1.1994 - acc: 0.5325

 39680/124800 [========>.....................] - ETA: 33s - loss: 1.1992 - acc: 0.5327

 39936/124800 [========>.....................] - ETA: 33s - loss: 1.1990 - acc: 0.5329

 40192/124800 [========>.....................] - ETA: 33s - loss: 1.1984 - acc: 0.5331

 40448/124800 [========>.....................] - ETA: 32s - loss: 1.1981 - acc: 0.5332

 40576/124800 [========>.....................] - ETA: 32s - loss: 1.1981 - acc: 0.5330



 40832/124800 [========>.....................] - ETA: 32s - loss: 1.1985 - acc: 0.5327

 40960/124800 [========>.....................] - ETA: 32s - loss: 1.1986 - acc: 0.5326

 41216/124800 [========>.....................] - ETA: 32s - loss: 1.1981 - acc: 0.5327



 41344/124800 [========>.....................] - ETA: 32s - loss: 1.1982 - acc: 0.5327



 41472/124800 [========>.....................] - ETA: 32s - loss: 1.1982 - acc: 0.5326



 41728/124800 [=========>....................] - ETA: 32s - loss: 1.1975 - acc: 0.5328

 41984/124800 [=========>....................] - ETA: 32s - loss: 1.1970 - acc: 0.5331

 42240/124800 [=========>....................] - ETA: 32s - loss: 1.1964 - acc: 0.5335

 42496/124800 [=========>....................] - ETA: 31s - loss: 1.1958 - acc: 0.5338

 42624/124800 [=========>....................] - ETA: 31s - loss: 1.1956 - acc: 0.5339

 42880/124800 [=========>....................] - ETA: 31s - loss: 1.1952 - acc: 0.5340

 43008/124800 [=========>....................] - ETA: 31s - loss: 1.1946 - acc: 0.5344

 43264/124800 [=========>....................] - ETA: 31s - loss: 1.1938 - acc: 0.5347



 43520/124800 [=========>....................] - ETA: 31s - loss: 1.1934 - acc: 0.5349

 43776/124800 [=========>....................] - ETA: 31s - loss: 1.1934 - acc: 0.5348

 44032/124800 [=========>....................] - ETA: 31s - loss: 1.1928 - acc: 0.5349

 44288/124800 [=========>....................] - ETA: 31s - loss: 1.1926 - acc: 0.5349

 44544/124800 [=========>....................] - ETA: 31s - loss: 1.1925 - acc: 0.5350

 44800/124800 [=========>....................] - ETA: 30s - loss: 1.1923 - acc: 0.5351

 45056/124800 [=========>....................] - ETA: 30s - loss: 1.1921 - acc: 0.5350

 45312/124800 [=========>....................] - ETA: 30s - loss: 1.1917 - acc: 0.5352

 45568/124800 [=========>....................] - ETA: 30s - loss: 1.1917 - acc: 0.5352



 45824/124800 [==========>...................] - ETA: 30s - loss: 1.1911 - acc: 0.5355

 46080/124800 [==========>...................] - ETA: 30s - loss: 1.1906 - acc: 0.5357

 46336/124800 [==========>...................] - ETA: 30s - loss: 1.1900 - acc: 0.5357

 46592/124800 [==========>...................] - ETA: 30s - loss: 1.1898 - acc: 0.5357

 46848/124800 [==========>...................] - ETA: 29s - loss: 1.1898 - acc: 0.5358

 46976/124800 [==========>...................] - ETA: 29s - loss: 1.1900 - acc: 0.5356

 47232/124800 [==========>...................] - ETA: 29s - loss: 1.1896 - acc: 0.5358

 47488/124800 [==========>...................] - ETA: 29s - loss: 1.1891 - acc: 0.5360

 47744/124800 [==========>...................] - ETA: 29s - loss: 1.1887 - acc: 0.5362

 48000/124800 [==========>...................] - ETA: 29s - loss: 1.1880 - acc: 0.5365

 48256/124800 [==========>...................] - ETA: 29s - loss: 1.1874 - acc: 0.5367

 48512/124800 [==========>...................] - ETA: 29s - loss: 1.1863 - acc: 0.5372

 48768/124800 [==========>...................] - ETA: 29s - loss: 1.1858 - acc: 0.5373

 48896/124800 [==========>...................] - ETA: 28s - loss: 1.1857 - acc: 0.5373

 49024/124800 [==========>...................] - ETA: 28s - loss: 1.1854 - acc: 0.5374



 49280/124800 [==========>...................] - ETA: 28s - loss: 1.1848 - acc: 0.5377



 49536/124800 [==========>...................] - ETA: 28s - loss: 1.1843 - acc: 0.5378

 49664/124800 [==========>...................] - ETA: 28s - loss: 1.1840 - acc: 0.5379

 49920/124800 [===========>..................] - ETA: 28s - loss: 1.1833 - acc: 0.5383

 50176/124800 [===========>..................] - ETA: 28s - loss: 1.1831 - acc: 0.5385

 50432/124800 [===========>..................] - ETA: 28s - loss: 1.1825 - acc: 0.5388

 50688/124800 [===========>..................] - ETA: 28s - loss: 1.1820 - acc: 0.5391

 50944/124800 [===========>..................] - ETA: 28s - loss: 1.1819 - acc: 0.5391

 51072/124800 [===========>..................] - ETA: 28s - loss: 1.1818 - acc: 0.5390

 51200/124800 [===========>..................] - ETA: 27s - loss: 1.1816 - acc: 0.5391



 51456/124800 [===========>..................] - ETA: 27s - loss: 1.1814 - acc: 0.5391

 51712/124800 [===========>..................] - ETA: 27s - loss: 1.1811 - acc: 0.5392

 51840/124800 [===========>..................] - ETA: 27s - loss: 1.1807 - acc: 0.5395

 52096/124800 [===========>..................] - ETA: 27s - loss: 1.1801 - acc: 0.5398

 52352/124800 [===========>..................] - ETA: 27s - loss: 1.1797 - acc: 0.5399

 52480/124800 [===========>..................] - ETA: 27s - loss: 1.1795 - acc: 0.5400

 52736/124800 [===========>..................] - ETA: 27s - loss: 1.1789 - acc: 0.5403

 52864/124800 [===========>..................] - ETA: 27s - loss: 1.1786 - acc: 0.5403

 53120/124800 [===========>..................] - ETA: 27s - loss: 1.1779 - acc: 0.5407



 53376/124800 [===========>..................] - ETA: 27s - loss: 1.1773 - acc: 0.5410

 53632/124800 [===========>..................] - ETA: 26s - loss: 1.1770 - acc: 0.5410

 53888/124800 [===========>..................] - ETA: 26s - loss: 1.1763 - acc: 0.5414

 54144/124800 [============>.................] - ETA: 26s - loss: 1.1758 - acc: 0.5417

 54400/124800 [============>.................] - ETA: 26s - loss: 1.1752 - acc: 0.5419

 54528/124800 [============>.................] - ETA: 26s - loss: 1.1754 - acc: 0.5418



 54656/124800 [============>.................] - ETA: 26s - loss: 1.1755 - acc: 0.5417



 54912/124800 [============>.................] - ETA: 26s - loss: 1.1751 - acc: 0.5419

 55040/124800 [============>.................] - ETA: 26s - loss: 1.1751 - acc: 0.5418



 55168/124800 [============>.................] - ETA: 26s - loss: 1.1752 - acc: 0.5417

 55424/124800 [============>.................] - ETA: 26s - loss: 1.1747 - acc: 0.5419

 55680/124800 [============>.................] - ETA: 26s - loss: 1.1744 - acc: 0.5420

 55936/124800 [============>.................] - ETA: 26s - loss: 1.1741 - acc: 0.5420

 56192/124800 [============>.................] - ETA: 25s - loss: 1.1742 - acc: 0.5419

 56320/124800 [============>.................] - ETA: 25s - loss: 1.1741 - acc: 0.5419

 56576/124800 [============>.................] - ETA: 25s - loss: 1.1736 - acc: 0.5421

 56832/124800 [============>.................] - ETA: 25s - loss: 1.1732 - acc: 0.5422

 57088/124800 [============>.................] - ETA: 25s - loss: 1.1724 - acc: 0.5426

 57344/124800 [============>.................] - ETA: 25s - loss: 1.1719 - acc: 0.5428

 57600/124800 [============>.................] - ETA: 25s - loss: 1.1716 - acc: 0.5430

 57856/124800 [============>.................] - ETA: 25s - loss: 1.1716 - acc: 0.5430

 58112/124800 [============>.................] - ETA: 25s - loss: 1.1711 - acc: 0.5433

 58240/124800 [=============>................] - ETA: 25s - loss: 1.1706 - acc: 0.5435

 58368/124800 [=============>................] - ETA: 24s - loss: 1.1705 - acc: 0.5436

 58624/124800 [=============>................] - ETA: 24s - loss: 1.1700 - acc: 0.5438

 58880/124800 [=============>................] - ETA: 24s - loss: 1.1698 - acc: 0.5437

 59136/124800 [=============>................] - ETA: 24s - loss: 1.1693 - acc: 0.5439

 59392/124800 [=============>................] - ETA: 24s - loss: 1.1685 - acc: 0.5442

 59648/124800 [=============>................] - ETA: 24s - loss: 1.1678 - acc: 0.5445

 59904/124800 [=============>................] - ETA: 24s - loss: 1.1677 - acc: 0.5445

 60160/124800 [=============>................] - ETA: 24s - loss: 1.1675 - acc: 0.5445

 60416/124800 [=============>................] - ETA: 24s - loss: 1.1674 - acc: 0.5444

 60672/124800 [=============>................] - ETA: 23s - loss: 1.1669 - acc: 0.5446



 60928/124800 [=============>................] - ETA: 23s - loss: 1.1664 - acc: 0.5449

 61184/124800 [=============>................] - ETA: 23s - loss: 1.1659 - acc: 0.5451

 61440/124800 [=============>................] - ETA: 23s - loss: 1.1656 - acc: 0.5452

 61568/124800 [=============>................] - ETA: 23s - loss: 1.1652 - acc: 0.5454

 61824/124800 [=============>................] - ETA: 23s - loss: 1.1649 - acc: 0.5456

 61952/124800 [=============>................] - ETA: 23s - loss: 1.1648 - acc: 0.5456

 62208/124800 [=============>................] - ETA: 23s - loss: 1.1644 - acc: 0.5456

 62464/124800 [==============>...............] - ETA: 23s - loss: 1.1640 - acc: 0.5457

 62720/124800 [==============>...............] - ETA: 23s - loss: 1.1639 - acc: 0.5458

 62976/124800 [==============>...............] - ETA: 22s - loss: 1.1635 - acc: 0.5460

 63232/124800 [==============>...............] - ETA: 22s - loss: 1.1630 - acc: 0.5462

 63488/124800 [==============>...............] - ETA: 22s - loss: 1.1625 - acc: 0.5465

 63744/124800 [==============>...............] - ETA: 22s - loss: 1.1623 - acc: 0.5467

 64000/124800 [==============>...............] - ETA: 22s - loss: 1.1617 - acc: 0.5470

 64256/124800 [==============>...............] - ETA: 22s - loss: 1.1614 - acc: 0.5471

 64512/124800 [==============>...............] - ETA: 22s - loss: 1.1610 - acc: 0.5472

 64768/124800 [==============>...............] - ETA: 22s - loss: 1.1605 - acc: 0.5474

 65024/124800 [==============>...............] - ETA: 22s - loss: 1.1602 - acc: 0.5474

 65280/124800 [==============>...............] - ETA: 21s - loss: 1.1600 - acc: 0.5475



 65536/124800 [==============>...............] - ETA: 21s - loss: 1.1596 - acc: 0.5476



 65792/124800 [==============>...............] - ETA: 21s - loss: 1.1591 - acc: 0.5479



 66048/124800 [==============>...............] - ETA: 21s - loss: 1.1588 - acc: 0.5481



 66304/124800 [==============>...............] - ETA: 21s - loss: 1.1582 - acc: 0.5483

 66560/124800 [===============>..............] - ETA: 21s - loss: 1.1580 - acc: 0.5482

 66816/124800 [===============>..............] - ETA: 21s - loss: 1.1577 - acc: 0.5483

 67072/124800 [===============>..............] - ETA: 21s - loss: 1.1569 - acc: 0.5486

 67328/124800 [===============>..............] - ETA: 21s - loss: 1.1564 - acc: 0.5488

 67584/124800 [===============>..............] - ETA: 20s - loss: 1.1561 - acc: 0.5488

 67840/124800 [===============>..............] - ETA: 20s - loss: 1.1556 - acc: 0.5491

 68096/124800 [===============>..............] - ETA: 20s - loss: 1.1550 - acc: 0.5495

 68352/124800 [===============>..............] - ETA: 20s - loss: 1.1549 - acc: 0.5494

 68608/124800 [===============>..............] - ETA: 20s - loss: 1.1547 - acc: 0.5494

 68864/124800 [===============>..............] - ETA: 20s - loss: 1.1545 - acc: 0.5495

 69120/124800 [===============>..............] - ETA: 20s - loss: 1.1541 - acc: 0.5498

 69376/124800 [===============>..............] - ETA: 20s - loss: 1.1536 - acc: 0.5500

 69632/124800 [===============>..............] - ETA: 20s - loss: 1.1531 - acc: 0.5504

 69760/124800 [===============>..............] - ETA: 20s - loss: 1.1532 - acc: 0.5502



 70016/124800 [===============>..............] - ETA: 19s - loss: 1.1526 - acc: 0.5506

 70272/124800 [===============>..............] - ETA: 19s - loss: 1.1523 - acc: 0.5507

 70528/124800 [===============>..............] - ETA: 19s - loss: 1.1519 - acc: 0.5508

 70784/124800 [================>.............] - ETA: 19s - loss: 1.1517 - acc: 0.5508

 71040/124800 [================>.............] - ETA: 19s - loss: 1.1513 - acc: 0.5509

 71296/124800 [================>.............] - ETA: 19s - loss: 1.1512 - acc: 0.5509

 71552/124800 [================>.............] - ETA: 19s - loss: 1.1509 - acc: 0.5512

 71808/124800 [================>.............] - ETA: 19s - loss: 1.1503 - acc: 0.5515

 72064/124800 [================>.............] - ETA: 19s - loss: 1.1496 - acc: 0.5517

 72320/124800 [================>.............]

 - ETA: 18s - loss: 1.1490 - acc: 0.5520



 72576/124800 [================>.............] - ETA: 18s - loss: 1.1487 - acc: 0.5521



 72832/124800 [================>.............] - ETA: 18s - loss: 1.1483 - acc: 0.5523

 73088/124800 [================>.............] - ETA: 18s - loss: 1.1478 - acc: 0.5523



 73344/124800 [================>.............] - ETA: 18s - loss: 1.1473 - acc: 0.5526

 73600/124800 [================>.............] - ETA: 18s - loss: 1.1472 - acc: 0.5526

 73856/124800 [================>.............] - ETA: 18s - loss: 1.1468 - acc: 0.5528

 74112/124800 [================>.............] - ETA: 18s - loss: 1.1466 - acc: 0.5530

 74368/124800 [================>.............] - ETA: 18s - loss: 1.1465 - acc: 0.5530

 74624/124800 [================>.............] - ETA: 18s - loss: 1.1464 - acc: 0.5530



 74880/124800 [=================>............] - ETA: 18s - loss: 1.1460 - acc: 0.5532

 75008/124800 [=================>............] - ETA: 17s - loss: 1.1461 - acc: 0.5531

 75136/124800 [=================>............] - ETA: 17s - loss: 1.1459 - acc: 0.5532

 75392/124800 [=================>............] - ETA: 17s - loss: 1.1454 - acc: 0.5534

 75648/124800 [=================>............] - ETA: 17s - loss: 1.1453 - acc: 0.5535

 75904/124800 [=================>............] - ETA: 17s - loss: 1.1447 - acc: 0.5537

 76032/124800 [=================>............] - ETA: 17s - loss: 1.1447 - acc: 0.5537

 76288/124800 [=================>............] - ETA: 17s - loss: 1.1445 - acc: 0.5537

 76544/124800 [=================>............] - ETA: 17s - loss: 1.1441 - acc: 0.5537

 76800/124800 [=================>............] - ETA: 17s - loss: 1.1438 - acc: 0.5537

 76928/124800 [=================>............] - ETA: 17s - loss: 1.1435 - acc: 0.5538

 77184/124800 [=================>............] - ETA: 17s - loss: 1.1432 - acc: 0.5539

 77312/124800 [=================>............] - ETA: 17s - loss: 1.1430 - acc: 0.5539

 77568/124800 [=================>............] - ETA: 17s - loss: 1.1427 - acc: 0.5541

 77824/124800 [=================>............] - ETA: 16s - loss: 1.1425 - acc: 0.5541

 77952/124800 [=================>............] - ETA: 16s - loss: 1.1424 - acc: 0.5541

 78208/124800 [=================>............] - ETA: 16s - loss: 1.1420 - acc: 0.5543



 78336/124800 [=================>............] - ETA: 16s - loss: 1.1418 - acc: 0.5544

 78592/124800 [=================>............] - ETA: 16s - loss: 1.1416 - acc: 0.5543

 78848/124800 [=================>............] - ETA: 16s - loss: 1.1412 - acc: 0.5545

 79104/124800 [==================>...........] - ETA: 16s - loss: 1.1409 - acc: 0.5546

 79360/124800 [==================>...........] - ETA: 16s - loss: 1.1404 - acc: 0.5548

 79616/124800 [==================>...........] - ETA: 16s - loss: 1.1400 - acc: 0.5551

 79872/124800 [==================>...........] - ETA: 16s - loss: 1.1396 - acc: 0.5551

 80128/124800 [==================>...........] - ETA: 16s - loss: 1.1392 - acc: 0.5553

 80384/124800 [==================>...........] - ETA: 15s - loss: 1.1390 - acc: 0.5555

 80640/124800 [==================>...........] - ETA: 15s - loss: 1.1386 - acc: 0.5556

 80768/124800 [==================>...........] - ETA: 15s - loss: 1.1383 - acc: 0.5557

 81024/124800 [==================>...........] - ETA: 15s - loss: 1.1379 - acc: 0.5558

 81152/124800 [==================>...........] - ETA: 15s - loss: 1.1376 - acc: 0.5559

 81408/124800 [==================>...........] - ETA: 15s - loss: 1.1371 - acc: 0.5561



 81664/124800 [==================>...........] - ETA: 15s - loss: 1.1366 - acc: 0.5564

 81792/124800 [==================>...........] - ETA: 15s - loss: 1.1365 - acc: 0.5564



 81920/124800 [==================>...........] - ETA: 15s - loss: 1.1363 - acc: 0.5564



 82176/124800 [==================>...........] - ETA: 15s - loss: 1.1358 - acc: 0.5566

 82432/124800 [==================>...........] - ETA: 15s - loss: 1.1358 - acc: 0.5566

 82688/124800 [==================>...........] - ETA: 15s - loss: 1.1352 - acc: 0.5568



 82944/124800 [==================>...........] - ETA: 15s - loss: 1.1347 - acc: 0.5570

 83200/124800 [===================>..........] - ETA: 14s - loss: 1.1346 - acc: 0.5570



 83456/124800 [===================>..........] - ETA: 14s - loss: 1.1342 - acc: 0.5571

 83712/124800 [===================>..........] - ETA: 14s - loss: 1.1339 - acc: 0.5573

 83840/124800 [===================>..........] - ETA: 14s - loss: 1.1338 - acc: 0.5573

 84096/124800 [===================>..........] - ETA: 14s - loss: 1.1331 - acc: 0.5577

 84352/124800 [===================>..........] - ETA: 14s - loss: 1.1327 - acc: 0.5579

 84480/124800 [===================>..........] - ETA: 14s - loss: 1.1324 - acc: 0.5580

 84736/124800 [===================>..........] - ETA: 14s - loss: 1.1323 - acc: 0.5580

 84992/124800 [===================>..........] - ETA: 14s - loss: 1.1320 - acc: 0.5582

 85248/124800 [===================>..........] - ETA: 14s - loss: 1.1315 - acc: 0.5584

 85504/124800 [===================>..........] - ETA: 14s - loss: 1.1313 - acc: 0.5584

 85760/124800 [===================>..........] - ETA: 14s - loss: 1.1309 - acc: 0.5585

 85888/124800 [===================>..........] - ETA: 13s - loss: 1.1307 - acc: 0.5586



 86144/124800 [===================>..........] - ETA: 13s - loss: 1.1302 - acc: 0.5589



 86400/124800 [===================>..........] - ETA: 13s - loss: 1.1299 - acc: 0.5590

 86656/124800 [===================>..........] - ETA: 13s - loss: 1.1298 - acc: 0.5591

 86912/124800 [===================>..........] - ETA: 13s - loss: 1.1294 - acc: 0.5593

 87168/124800 [===================>..........] - ETA: 13s - loss: 1.1289 - acc: 0.5595

 87424/124800 [====================>.........] - ETA: 13s - loss: 1.1283 - acc: 0.5597

 87552/124800 [====================>.........] - ETA: 13s - loss: 1.1282 - acc: 0.5598



 87808/124800 [====================>.........] - ETA: 13s - loss: 1.1278 - acc: 0.5599



 88064/124800 [====================>.........] - ETA: 13s - loss: 1.1275 - acc: 0.5600

 88320/124800 [====================>.........] - ETA: 13s - loss: 1.1274 - acc: 0.5601

 88576/124800 [====================>.........] - ETA: 12s - loss: 1.1271 - acc: 0.5601

 88832/124800 [====================>.........] - ETA: 12s - loss: 1.1267 - acc: 0.5602

 88960/124800 [====================>.........] - ETA: 12s - loss: 1.1266 - acc: 0.5603

 89216/124800 [====================>.........] - ETA: 12s - loss: 1.1265 - acc: 0.5603

 89472/124800 [====================>.........] - ETA: 12s - loss: 1.1264 - acc: 0.5603

 89728/124800 [====================>.........] - ETA: 12s - loss: 1.1260 - acc: 0.5603

 89856/124800 [====================>.........] - ETA: 12s - loss: 1.1257 - acc: 0.5604

 90112/124800 [====================>.........] - ETA: 12s - loss: 1.1252 - acc: 0.5607

 90368/124800 [====================>.........] - ETA: 12s - loss: 1.1250 - acc: 0.5607

 90624/124800 [====================>.........] - ETA: 12s - loss: 1.1246 - acc: 0.5608

 90752/124800 [====================>.........] - ETA: 12s - loss: 1.1244 - acc: 0.5609

 91008/124800 [====================>.........] - ETA: 12s - loss: 1.1244 - acc: 0.5609



 91136/124800 [====================>.........] - ETA: 12s - loss: 1.1242 - acc: 0.5611



 91264/124800 [====================>.........] - ETA: 11s - loss: 1.1239 - acc: 0.5613

 91520/124800 [=====================>........] - ETA: 11s - loss: 1.1234 - acc: 0.5613

 91776/124800 [=====================>........] - ETA: 11s - loss: 1.1232 - acc: 0.5614

 92032/124800 [=====================>........] - ETA: 11s - loss: 1.1229 - acc: 0.5616

 92160/124800 [=====================>........] - ETA: 11s - loss: 1.1227 - acc: 0.5617

 92416/124800 [=====================>........] - ETA: 11s - loss: 1.1223 - acc: 0.5618



 92672/124800 [=====================>........] - ETA: 11s - loss: 1.1222 - acc: 0.5618

 92800/124800 [=====================>........] - ETA: 11s - loss: 1.1221 - acc: 0.5619

 92928/124800 [=====================>........] - ETA: 11s - loss: 1.1220 - acc: 0.5619



 93184/124800 [=====================>........] - ETA: 11s - loss: 1.1218 - acc: 0.5620

 93440/124800 [=====================>........] - ETA: 11s - loss: 1.1214 - acc: 0.5621

 93696/124800 [=====================>........] - ETA: 11s - loss: 1.1209 - acc: 0.5623

 93824/124800 [=====================>........] - ETA: 11s - loss: 1.1206 - acc: 0.5624

 94080/124800 [=====================>........] - ETA: 10s - loss: 1.1200 - acc: 0.5625



 94336/124800 [=====================>........] - ETA: 10s - loss: 1.1201 - acc: 0.5625



 94592/124800 [=====================>........] - ETA: 10s - loss: 1.1196 - acc: 0.5626

 94848/124800 [=====================>........] - ETA: 10s - loss: 1.1193 - acc: 0.5627

 95104/124800 [=====================>........] - ETA: 10s - loss: 1.1190 - acc: 0.5628

 95360/124800 [=====================>........] - ETA: 10s - loss: 1.1188 - acc: 0.5629

 95616/124800 [=====================>........] - ETA: 10s - loss: 1.1186 - acc: 0.5630

 95872/124800 [======================>.......] - ETA: 10s - loss: 1.1181 - acc: 0.5632

 96128/124800 [======================>.......] - ETA: 10s - loss: 1.1178 - acc: 0.5633

 96256/124800 [======================>.......] - ETA: 10s - loss: 1.1176 - acc: 0.5634

 96512/124800 [======================>.......] - ETA: 10s - loss: 1.1172 - acc: 0.5636

 96768/124800 [======================>.......] - ETA: 9s - loss: 1.1168 - acc: 0.5637 

 97024/124800 [======================>.......] - ETA: 9s - loss: 1.1165 - acc: 0.5637

 97280/124800 [======================>.......] - ETA: 9s - loss: 1.1163 - acc: 0.5638



 97536/124800 [======================>.......] - ETA: 9s - loss: 1.1162 - acc: 0.5637

 97664/124800 [======================>.......] - ETA: 9s - loss: 1.1161 - acc: 0.5638

 97920/124800 [======================>.......] - ETA: 9s - loss: 1.1157 - acc: 0.5640

 98176/124800 [======================>.......] - ETA: 9s - loss: 1.1154 - acc: 0.5640

 98432/124800 [======================>.......] - ETA: 9s - loss: 1.1151 - acc: 0.5641



 98688/124800 [======================>.......] - ETA: 9s - loss: 1.1145 - acc: 0.5644



 98816/124800 [======================>.......] - ETA: 9s - loss: 1.1144 - acc: 0.5644



 98944/124800 [======================>.......] - ETA: 9s - loss: 1.1143 - acc: 0.5643

 99200/124800 [======================>.......] - ETA: 9s - loss: 1.1140 - acc: 0.5643

 99456/124800 [======================>.......] - ETA: 9s - loss: 1.1139 - acc: 0.5644

 99712/124800 [======================>.......] - ETA: 8s - loss: 1.1134 - acc: 0.5645

 99968/124800 [=======================>......] - ETA: 8s - loss: 1.1131 - acc: 0.5646

100224/124800 [=======================>......] - ETA: 8s - loss: 1.1129 - acc: 0.5646

100480/124800 [=======================>......] - ETA: 8s - loss: 1.1129 - acc: 0.5647

100608/124800 [=======================>......] - ETA: 8s - loss: 1.1126 - acc: 0.5648



100736/124800 [=======================>......] - ETA: 8s - loss: 1.1125 - acc: 0.5648



100992/124800 [=======================>......] - ETA: 8s - loss: 1.1121 - acc: 0.5650

101120/124800 [=======================>......] - ETA: 8s - loss: 1.1118 - acc: 0.5651

101376/124800 [=======================>......] - ETA: 8s - loss: 1.1116 - acc: 0.5651



101504/124800 [=======================>......] - ETA: 8s - loss: 1.1113 - acc: 0.5652

101760/124800 [=======================>......] - ETA: 8s - loss: 1.1109 - acc: 0.5653

101888/124800 [=======================>......] - ETA: 8s - loss: 1.1110 - acc: 0.5652

102144/124800 [=======================>......] - ETA: 8s - loss: 1.1106 - acc: 0.5653



102400/124800 [=======================>......] - ETA: 7s - loss: 1.1104 - acc: 0.5655

102656/124800 [=======================>......] - ETA: 7s - loss: 1.1100 - acc: 0.5657



102912/124800 [=======================>......] - ETA: 7s - loss: 1.1096 - acc: 0.5658



103168/124800 [=======================>......] - ETA: 7s - loss: 1.1093 - acc: 0.5659

103424/124800 [=======================>......] - ETA: 7s - loss: 1.1090 - acc: 0.5660

103680/124800 [=======================>......] - ETA: 7s - loss: 1.1087 - acc: 0.5661



103936/124800 [=======================>......] - ETA: 7s - loss: 1.1083 - acc: 0.5662

104064/124800 [========================>.....] - ETA: 7s - loss: 1.1081 - acc: 0.5663

104320/124800 [========================>.....] - ETA: 7s - loss: 1.1078 - acc: 0.5664

104576/124800 [========================>.....] - ETA: 7s - loss: 1.1075 - acc: 0.5665

104832/124800 [========================>.....] - ETA: 7s - loss: 1.1072 - acc: 0.5667

105088/124800 [========================>.....] - ETA: 7s - loss: 1.1071 - acc: 0.5667

105216/124800 [========================>.....] - ETA: 6s - loss: 1.1068 - acc: 0.5668

105472/124800 [========================>.....] - ETA: 6s - loss: 1.1064 - acc: 0.5669



105728/124800 [========================>.....] - ETA: 6s - loss: 1.1061 - acc: 0.5671

105856/124800 [========================>.....] - ETA: 6s - loss: 1.1061 - acc: 0.5670

106112/124800 [========================>.....] - ETA: 6s - loss: 1.1058 - acc: 0.5672

106368/124800 [========================>.....] - ETA: 6s - loss: 1.1054 - acc: 0.5673

106624/124800 [========================>.....] - ETA: 6s - loss: 1.1050 - acc: 0.5675

106880/124800 [========================>.....] - ETA: 6s - loss: 1.1047 - acc: 0.5676

107136/124800 [========================>.....] - ETA: 6s - loss: 1.1041 - acc: 0.5679

107392/124800 [========================>.....] - ETA: 6s - loss: 1.1039 - acc: 0.5680

107520/124800 [========================>.....] - ETA: 6s - loss: 1.1038 - acc: 0.5680

107776/124800 [========================>.....] - ETA: 6s - loss: 1.1035 - acc: 0.5681

108032/124800 [========================>.....] - ETA: 5s - loss: 1.1035 - acc: 0.5681

108288/124800 [=========================>....] - ETA: 5s - loss: 1.1033 - acc: 0.5681

108544/124800 [=========================>....] - ETA: 5s - loss: 1.1028 - acc: 0.5683

108672/124800 [=========================>....] - ETA: 5s - loss: 1.1026 - acc: 0.5683

108800/124800 [=========================>....] - ETA: 5s - loss: 1.1024 - acc: 0.5684

108928/124800 [=========================>....] - ETA: 5s - loss: 1.1024 - acc: 0.5684

109056/124800 [=========================>....] - ETA: 5s - loss: 1.1023 - acc: 0.5685

109312/124800 [=========================>....] - ETA: 5s - loss: 1.1020 - acc: 0.5686



109440/124800 [=========================>....] - ETA: 5s - loss: 1.1018 - acc: 0.5687



109568/124800 [=========================>....] - ETA: 5s - loss: 1.1016 - acc: 0.5688



109824/124800 [=========================>....] - ETA: 5s - loss: 1.1013 - acc: 0.5689

110080/124800 [=========================>....] - ETA: 5s - loss: 1.1009 - acc: 0.5690

110336/124800 [=========================>....] - ETA: 5s - loss: 1.1008 - acc: 0.5691

110592/124800 [=========================>....] - ETA: 5s - loss: 1.1005 - acc: 0.5692

110848/124800 [=========================>....] - ETA: 4s - loss: 1.1000 - acc: 0.5694

111104/124800 [=========================>....] - ETA: 4s - loss: 1.0999 - acc: 0.5695

111360/124800 [=========================>....] - ETA: 4s - loss: 1.0996 - acc: 0.5695

111616/124800 [=========================>....] - ETA: 4s - loss: 1.0994 - acc: 0.5696

111872/124800 [=========================>....] - ETA: 4s - loss: 1.0990 - acc: 0.5697

112128/124800 [=========================>....] - ETA: 4s - loss: 1.0988 - acc: 0.5697

112256/124800 [=========================>....] - ETA: 4s - loss: 1.0987 - acc: 0.5697

112512/124800 [==========================>...] - ETA: 4s - loss: 1.0984 - acc: 0.5698

112640/124800 [==========================>...] - ETA: 4s - loss: 1.0982 - acc: 0.5698

112768/124800 [==========================>...] - ETA: 4s - loss: 1.0981 - acc: 0.5699



113024/124800 [==========================>...] - ETA: 4s - loss: 1.0977 - acc: 0.5701

113280/124800 [==========================>...] - ETA: 4s - loss: 1.0974 - acc: 0.5702

113536/124800 [==========================>...] - ETA: 3s - loss: 1.0973 - acc: 0.5703

113792/124800 [==========================>...] - ETA: 3s - loss: 1.0970 - acc: 0.5704

114048/124800 [==========================>...] - ETA: 3s - loss: 1.0967 - acc: 0.5706

114304/124800 [==========================>...] - ETA: 3s - loss: 1.0964 - acc: 0.5707

114560/124800 [==========================>...] - ETA: 3s - loss: 1.0959 - acc: 0.5709

114816/124800 [==========================>...] - ETA: 3s - loss: 1.0959 - acc: 0.5709

115072/124800 [==========================>...] - ETA: 3s - loss: 1.0955 - acc: 0.5711

115328/124800 [==========================>...] - ETA: 3s - loss: 1.0956 - acc: 0.5711

115584/124800 [==========================>...] - ETA: 3s - loss: 1.0951 - acc: 0.5712

115840/124800 [==========================>...] - ETA: 3s - loss: 1.0946 - acc: 0.5715

115968/124800 [==========================>...] - ETA: 3s - loss: 1.0945 - acc: 0.5715

116224/124800 [==========================>...] - ETA: 3s - loss: 1.0942 - acc: 0.5715

116480/124800 [===========================>..] - ETA: 2s - loss: 1.0940 - acc: 0.5715

116736/124800 [===========================>..] - ETA: 2s - loss: 1.0936 - acc: 0.5717



116992/124800 [===========================>..] - ETA: 2s - loss: 1.0933 - acc: 0.5717

117248/124800 [===========================>..] - ETA: 2s - loss: 1.0931 - acc: 0.5718

117504/124800 [===========================>..] - ETA: 2s - loss: 1.0930 - acc: 0.5719

117760/124800 [===========================>..] - ETA: 2s - loss: 1.0927 - acc: 0.5720

118016/124800 [===========================>..] - ETA: 2s - loss: 1.0924 - acc: 0.5721

118272/124800 [===========================>..] - ETA: 2s - loss: 1.0920 - acc: 0.5722



118528/124800 [===========================>..] - ETA: 2s - loss: 1.0915 - acc: 0.5723

118656/124800 [===========================>..] - ETA: 2s - loss: 1.0914 - acc: 0.5724

118912/124800 [===========================>..] - ETA: 2s - loss: 1.0910 - acc: 0.5725



119168/124800 [===========================>..] - ETA: 1s - loss: 1.0905 - acc: 0.5727

119424/124800 [===========================>..] - ETA: 1s - loss: 1.0902 - acc: 0.5728



119552/124800 [===========================>..] - ETA: 1s - loss: 1.0903 - acc: 0.5728

119680/124800 [===========================>..] - ETA: 1s - loss: 1.0901 - acc: 0.5729

119936/124800 [===========================>..] - ETA: 1s - loss: 1.0898 - acc: 0.5730



120192/124800 [===========================>..] - ETA: 1s - loss: 1.0895 - acc: 0.5731

120448/124800 [===========================>..] - ETA: 1s - loss: 1.0892 - acc: 0.5731

120704/124800 [============================>.] - ETA: 1s - loss: 1.0890 - acc: 0.5732

120960/124800 [============================>.] - ETA: 1s - loss: 1.0888 - acc: 0.5732

121088/124800 [============================>.] - ETA: 1s - loss: 1.0887 - acc: 0.5733

121344/124800 [============================>.] - ETA: 1s - loss: 1.0883 - acc: 0.5734

121600/124800 [============================>.] - ETA: 1s - loss: 1.0880 - acc: 0.5735

121728/124800 [============================>.] - ETA: 1s - loss: 1.0878 - acc: 0.5736

121984/124800 [============================>.] - ETA: 0s - loss: 1.0876 - acc: 0.5737

122240/124800 [============================>.] - ETA: 0s - loss: 1.0874 - acc: 0.5737

122368/124800 [============================>.] - ETA: 0s - loss: 1.0872 - acc: 0.5738



122496/124800 [============================>.] - ETA: 0s - loss: 1.0871 - acc: 0.5738

122624/124800 [============================>.] - ETA: 0s - loss: 1.0869 - acc: 0.5740



122880/124800 [============================>.] - ETA: 0s - loss: 1.0865 - acc: 0.5741

123008/124800 [============================>.] - ETA: 0s - loss: 1.0863 - acc: 0.5741

123264/124800 [============================>.] - ETA: 0s - loss: 1.0861 - acc: 0.5742

123392/124800 [============================>.] - ETA: 0s - loss: 1.0859 - acc: 0.5742

123648/124800 [============================>.] - ETA: 0s - loss: 1.0857 - acc: 0.5742

123904/124800 [============================>.] - ETA: 0s - loss: 1.0854 - acc: 0.5743

124160/124800 [============================>.] - ETA: 0s - loss: 1.0852 - acc: 0.5744

124288/124800 [============================>.] - ETA: 0s - loss: 1.0850 - acc: 0.5745

124544/124800 [============================>.] - ETA: 0s - loss: 1.0846 - acc: 0.5747

124800/124800 [==============================] - 47s 377us/step - loss: 1.0843 - acc: 0.5748 - val_loss: 1.0820 - val_acc: 0.5632


Epoch 2/100
   128/124800 [..............................] - ETA: 57s - loss: 0.9101 - acc: 0.6328

   384/124800 [..............................] - ETA: 44s - loss: 0.8773 - acc: 0.6562

   640/124800 [..............................] - ETA: 41s - loss: 0.8760 - acc: 0.6562

   768/124800 [..............................] - ETA: 43s - loss: 0.8909 - acc: 0.6576



  1024/124800 [..............................] - ETA: 41s - loss: 0.8643 - acc: 0.6689

  1280/124800 [..............................] - ETA: 40s - loss: 0.8666 - acc: 0.6633



  1536/124800 [..............................] - ETA: 41s - loss: 0.8725 - acc: 0.6569



  1792/124800 [..............................] - ETA: 41s - loss: 0.8773 - acc: 0.6585

  2048/124800 [..............................] - ETA: 40s - loss: 0.8782 - acc: 0.6577

  2304/124800 [..............................] - ETA: 40s - loss: 0.8783 - acc: 0.6576

  2560/124800 [..............................] - ETA: 40s - loss: 0.8827 - acc: 0.6508



  2816/124800 [..............................] - ETA: 40s - loss: 0.8825 - acc: 0.6520

  2944/124800 [..............................] - ETA: 41s - loss: 0.8801 - acc: 0.6515

  3200/124800 [..............................] - ETA: 41s - loss: 0.8780 - acc: 0.6500

  3456/124800 [..............................] - ETA: 40s - loss: 0.8795 - acc: 0.6481

  3712/124800 [..............................] - ETA: 40s - loss: 0.8780 - acc: 0.6495



  3840/124800 [..............................] - ETA: 40s - loss: 0.8782 - acc: 0.6495

  3968/124800 [..............................] - ETA: 40s - loss: 0.8788 - acc: 0.6482

  4224/124800 [>.............................] - ETA: 40s - loss: 0.8832 - acc: 0.6461

  4480/124800 [>.............................] - ETA: 40s - loss: 0.8805 - acc: 0.6473

  4736/124800 [>.............................] - ETA: 39s - loss: 0.8827 - acc: 0.6463

  4992/124800 [>.............................] - ETA: 39s - loss: 0.8810 - acc: 0.6476

  5248/124800 [>.............................] - ETA: 39s - loss: 0.8855 - acc: 0.6450

  5504/124800 [>.............................] - ETA: 39s - loss: 0.8878 - acc: 0.6459

  5760/124800 [>.............................] - ETA: 39s - loss: 0.8899 - acc: 0.6458

  6016/124800 [>.............................] - ETA: 39s - loss: 0.8901 - acc: 0.6464

  6272/124800 [>.............................] - ETA: 39s - loss: 0.8907 - acc: 0.6464

  6528/124800 [>.............................] - ETA: 38s - loss: 0.8921 - acc: 0.6457

  6784/124800 [>.............................] - ETA: 38s - loss: 0.8915 - acc: 0.6461

  7040/124800 [>.............................] - ETA: 38s - loss: 0.8922 - acc: 0.6457



  7296/124800 [>.............................] - ETA: 38s - loss: 0.8945 - acc: 0.6435

  7424/124800 [>.............................] - ETA: 38s - loss: 0.8945 - acc: 0.6435

  7680/124800 [>.............................] - ETA: 38s - loss: 0.8943 - acc: 0.6445

  7936/124800 [>.............................] - ETA: 38s - loss: 0.8929 - acc: 0.6458

  8192/124800 [>.............................] - ETA: 38s - loss: 0.8942 - acc: 0.6456

  8448/124800 [=>............................] - ETA: 37s - loss: 0.8967 - acc: 0.6448

  8704/124800 [=>............................] - ETA: 37s - loss: 0.8969 - acc: 0.6444



  8960/124800 [=>............................] - ETA: 37s - loss: 0.8978 - acc: 0.6442



  9216/124800 [=>............................] - ETA: 37s - loss: 0.8957 - acc: 0.6454

  9472/124800 [=>............................] - ETA: 37s - loss: 0.8977 - acc: 0.6447

  9728/124800 [=>............................] - ETA: 37s - loss: 0.8982 - acc: 0.6447

  9856/124800 [=>............................] - ETA: 37s - loss: 0.8978 - acc: 0.6451

 10112/124800 [=>............................] - ETA: 37s - loss: 0.8971 - acc: 0.6457

 10368/124800 [=>............................] - ETA: 37s - loss: 0.8961 - acc: 0.6464

 10624/124800 [=>............................] - ETA: 37s - loss: 0.8963 - acc: 0.6465

 10752/124800 [=>............................] - ETA: 37s - loss: 0.8959 - acc: 0.6467

 11008/124800 [=>............................] - ETA: 37s - loss: 0.8964 - acc: 0.6467



 11136/124800 [=>............................] - ETA: 37s - loss: 0.8962 - acc: 0.6469

 11392/124800 [=>............................] - ETA: 37s - loss: 0.8963 - acc: 0.6467

 11520/124800 [=>............................] - ETA: 37s - loss: 0.8974 - acc: 0.6463

 11776/124800 [=>............................] - ETA: 37s - loss: 0.8955 - acc: 0.6471

 11904/124800 [=>............................] - ETA: 37s - loss: 0.8952 - acc: 0.6471

 12160/124800 [=>............................] - ETA: 37s - loss: 0.8969 - acc: 0.6463



 12288/124800 [=>............................] - ETA: 37s - loss: 0.8976 - acc: 0.6459

 12544/124800 [==>...........................] - ETA: 37s - loss: 0.8980 - acc: 0.6460

 12800/124800 [==>...........................] - ETA: 37s - loss: 0.8964 - acc: 0.6464

 13056/124800 [==>...........................] - ETA: 36s - loss: 0.8950 - acc: 0.6471

 13312/124800 [==>...........................] - ETA: 36s - loss: 0.8943 - acc: 0.6472

 13568/124800 [==>...........................] - ETA: 36s - loss: 0.8923 - acc: 0.6486

 13696/124800 [==>...........................] - ETA: 36s - loss: 0.8924 - acc: 0.6483



 13952/124800 [==>...........................] - ETA: 36s - loss: 0.8920 - acc: 0.6484

 14080/124800 [==>...........................] - ETA: 36s - loss: 0.8929 - acc: 0.6476



 14208/124800 [==>...........................] - ETA: 36s - loss: 0.8932 - acc: 0.6472

 14464/124800 [==>...........................] - ETA: 36s - loss: 0.8951 - acc: 0.6469

 14592/124800 [==>...........................] - ETA: 36s - loss: 0.8953 - acc: 0.6469

 14848/124800 [==>...........................] - ETA: 36s - loss: 0.8959 - acc: 0.6463

 15104/124800 [==>...........................] - ETA: 36s - loss: 0.8954 - acc: 0.6464

 15360/124800 [==>...........................] - ETA: 36s - loss: 0.8960 - acc: 0.6469

 15616/124800 [==>...........................] - ETA: 36s - loss: 0.8942 - acc: 0.6480

 15872/124800 [==>...........................] - ETA: 36s - loss: 0.8946 - acc: 0.6478

 16128/124800 [==>...........................] - ETA: 36s - loss: 0.8938 - acc: 0.6483

 16384/124800 [==>...........................] - ETA: 36s - loss: 0.8935 - acc: 0.6484

 16512/124800 [==>...........................] - ETA: 36s - loss: 0.8935 - acc: 0.6487

 16768/124800 [===>..........................] - ETA: 35s - loss: 0.8941 - acc: 0.6480

 17024/124800 [===>..........................] - ETA: 35s - loss: 0.8937 - acc: 0.6477

 17152/124800 [===>..........................] - ETA: 35s - loss: 0.8927 - acc: 0.6482

 17408/124800 [===>..........................] - ETA: 35s - loss: 0.8932 - acc: 0.6480

 17664/124800 [===>..........................] - ETA: 35s - loss: 0.8931 - acc: 0.6480

 17920/124800 [===>..........................] - ETA: 35s - loss: 0.8923 - acc: 0.6484

 18176/124800 [===>..........................] - ETA: 35s - loss: 0.8911 - acc: 0.6487

 18432/124800 [===>..........................] - ETA: 35s - loss: 0.8923 - acc: 0.6483

 18688/124800 [===>..........................] - ETA: 35s - loss: 0.8912 - acc: 0.6490

 18816/124800 [===>..........................] - ETA: 35s - loss: 0.8905 - acc: 0.6492

 19072/124800 [===>..........................] - ETA: 35s - loss: 0.8902 - acc: 0.6490



 19328/124800 [===>..........................] - ETA: 35s - loss: 0.8908 - acc: 0.6486

 19584/124800 [===>..........................] - ETA: 35s - loss: 0.8903 - acc: 0.6486

 19712/124800 [===>..........................] - ETA: 35s - loss: 0.8900 - acc: 0.6485

 19968/124800 [===>..........................] - ETA: 35s - loss: 0.8895 - acc: 0.6488

 20224/124800 [===>..........................] - ETA: 34s - loss: 0.8897 - acc: 0.6487

 20480/124800 [===>..........................] - ETA: 34s - loss: 0.8897 - acc: 0.6484

 20608/124800 [===>..........................] - ETA: 34s - loss: 0.8890 - acc: 0.6488

 20864/124800 [====>.........................] - ETA: 34s - loss: 0.8878 - acc: 0.6492

 20992/124800 [====>.........................] - ETA: 34s - loss: 0.8880 - acc: 0.6488

 21248/124800 [====>.........................] - ETA: 34s - loss: 0.8882 - acc: 0.6488

 21504/124800 [====>.........................] - ETA: 34s - loss: 0.8880 - acc: 0.6489

 21760/124800 [====>.........................] - ETA: 34s - loss: 0.8882 - acc: 0.6489

 22016/124800 [====>.........................] - ETA: 34s - loss: 0.8876 - acc: 0.6491

 22272/124800 [====>.........................] - ETA: 34s - loss: 0.8872 - acc: 0.6494

 22528/124800 [====>.........................] - ETA: 34s - loss: 0.8871 - acc: 0.6497

 22784/124800 [====>.........................] - ETA: 34s - loss: 0.8867 - acc: 0.6499



 23040/124800 [====>.........................] - ETA: 34s - loss: 0.8877 - acc: 0.6495



 23296/124800 [====>.........................] - ETA: 33s - loss: 0.8878 - acc: 0.6491

 23552/124800 [====>.........................] - ETA: 33s - loss: 0.8885 - acc: 0.6494

 23808/124800 [====>.........................] - ETA: 33s - loss: 0.8880 - acc: 0.6498



 23936/124800 [====>.........................] - ETA: 33s - loss: 0.8881 - acc: 0.6496

 24064/124800 [====>.........................] - ETA: 33s - loss: 0.8883 - acc: 0.6498

 24192/124800 [====>.........................] - ETA: 33s - loss: 0.8879 - acc: 0.6499

 24448/124800 [====>.........................] - ETA: 33s - loss: 0.8871 - acc: 0.6503

 24704/124800 [====>.........................] - ETA: 33s - loss: 0.8879 - acc: 0.6499

 24960/124800 [=====>........................] - ETA: 33s - loss: 0.8870 - acc: 0.6499

 25088/124800 [=====>........................] - ETA: 33s - loss: 0.8875 - acc: 0.6497



 25344/124800 [=====>........................] - ETA: 33s - loss: 0.8882 - acc: 0.6499

 25472/124800 [=====>........................] - ETA: 33s - loss: 0.8876 - acc: 0.6500

 25728/124800 [=====>........................] - ETA: 33s - loss: 0.8871 - acc: 0.6501

 25984/124800 [=====>........................] - ETA: 33s - loss: 0.8857 - acc: 0.6506

 26112/124800 [=====>........................] - ETA: 33s - loss: 0.8857 - acc: 0.6505

 26368/124800 [=====>........................] - ETA: 33s - loss: 0.8858 - acc: 0.6504

 26624/124800 [=====>........................] - ETA: 33s - loss: 0.8868 - acc: 0.6500

 26880/124800 [=====>........................] - ETA: 33s - loss: 0.8873 - acc: 0.6498

 27136/124800 [=====>........................] - ETA: 32s - loss: 0.8875 - acc: 0.6499

 27392/124800 [=====>........................] - ETA: 32s - loss: 0.8880 - acc: 0.6496

 27648/124800 [=====>........................] - ETA: 32s - loss: 0.8873 - acc: 0.6502

 27904/124800 [=====>........................] - ETA: 32s - loss: 0.8874 - acc: 0.6502

 28032/124800 [=====>........................] - ETA: 32s - loss: 0.8875 - acc: 0.6500

 28288/124800 [=====>........................] - ETA: 32s - loss: 0.8872 - acc: 0.6500

 28544/124800 [=====>........................] - ETA: 32s - loss: 0.8876 - acc: 0.6500

 28672/124800 [=====>........................] - ETA: 32s - loss: 0.8876 - acc: 0.6501

 28928/124800 [=====>........................] - ETA: 32s - loss: 0.8870 - acc: 0.6506

 29056/124800 [=====>........................] - ETA: 32s - loss: 0.8876 - acc: 0.6504

 29312/124800 [======>.......................] - ETA: 32s - loss: 0.8880 - acc: 0.6506



 29440/124800 [======>.......................] - ETA: 32s - loss: 0.8879 - acc: 0.6507

 29696/124800 [======>.......................] - ETA: 32s - loss: 0.8889 - acc: 0.6502

 29952/124800 [======>.......................] - ETA: 31s - loss: 0.8885 - acc: 0.6503

 30080/124800 [======>.......................] - ETA: 31s - loss: 0.8885 - acc: 0.6503

 30336/124800 [======>.......................] - ETA: 31s - loss: 0.8882 - acc: 0.6504

 30592/124800 [======>.......................] - ETA: 31s - loss: 0.8876 - acc: 0.6509

 30848/124800 [======>.......................] - ETA: 31s - loss: 0.8885 - acc: 0.6506

 31104/124800 [======>.......................] - ETA: 31s - loss: 0.8883 - acc: 0.6507

 31360/124800 [======>.......................] - ETA: 31s - loss: 0.8880 - acc: 0.6507

 31616/124800 [======>.......................] - ETA: 31s - loss: 0.8880 - acc: 0.6507

 31872/124800 [======>.......................] - ETA: 31s - loss: 0.8883 - acc: 0.6506

 32128/124800 [======>.......................] - ETA: 31s - loss: 0.8880 - acc: 0.6507

 32256/124800 [======>.......................] - ETA: 31s - loss: 0.8877 - acc: 0.6507

 32512/124800 [======>.......................] - ETA: 30s - loss: 0.8879 - acc: 0.6503

 32768/124800 [======>.......................] - ETA: 30s - loss: 0.8871 - acc: 0.6508

 33024/124800 [======>.......................] - ETA: 30s - loss: 0.8867 - acc: 0.6510

 33280/124800 [=======>......................] - ETA: 30s - loss: 0.8868 - acc: 0.6508

 33408/124800 [=======>......................] - ETA: 30s - loss: 0.8870 - acc: 0.6508

 33664/124800 [=======>......................] - ETA: 30s - loss: 0.8866 - acc: 0.6509

 33792/124800 [=======>......................] - ETA: 30s - loss: 0.8868 - acc: 0.6511

 33920/124800 [=======>......................] - ETA: 30s - loss: 0.8867 - acc: 0.6513

 34176/124800 [=======>......................] - ETA: 30s - loss: 0.8860 - acc: 0.6517

 34304/124800 [=======>......................] - ETA: 30s - loss: 0.8859 - acc: 0.6518

 34560/124800 [=======>......................] - ETA: 30s - loss: 0.8855 - acc: 0.6519

 34816/124800 [=======>......................] - ETA: 30s - loss: 0.8852 - acc: 0.6519

In [ ]:
from keras.models import load_model

model.save('RNN_model.h5')  # creates a HDF5 file 'my_model.h5'
del model  # deletes the existing model

# returns a compiled model
# identical to the previous one
model = load_model('RNN_model.h5')

y = model.predict(X_test)
print(y)

Index(['PhraseId', 'SentenceId', 'Phrase'], dtype='object')

Found 15288 unique tokens.


Found 15288 unique tokens.
